print("Lista de Compras:")
print("-----------------")
print("Arroz")
print("Feijão")
print("Ovos")
print("Leite")
print("Pão")
print("Frutas (maçã, banana, laranja)")
print("Legumes (tomate, alface, cenoura)")
print("Café")
print("Açúcar")
print("Papel higiênico")